[package]
name = "aleph-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "aleph_api"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20.0"
aleph_client = "3.0.0"
